import { createElement } from "react";
import type {
  SexyTableAssignee,
  SexyTableGroup,
  SexyTableIssue,
  SexyTablePriority,
  SexyTablePullRequestState,
} from "../types";
import { SexyTableStatusIcon } from "../SexyTableStatusIcon";

const people = {
  Maya: { id: "maya", name: "Maya Chen", image: "/assets/avatar-5.jpg" },
  Leo: { id: "leo", name: "Leo Hartman", image: "/assets/avatar-12.jpg" },
  Priya: { id: "priya", name: "Priya Raman", image: "/assets/avatar-16.jpg" },
  Harsh: {
    id: "harsh",
    name: "Harsh Singh",
    image: "/assets/avatar-harsh.webp",
  },
  Elena: { id: "elena", name: "Elena Rossi", image: "/assets/avatar-26.jpg" },
  Tom: { id: "tom", name: "Tom Okafor", image: "/assets/avatar-60.jpg" },
  Sam: { id: "sam", name: "Sam Whitaker", image: "/assets/avatar-59.jpg" },
} satisfies Record<string, SexyTableAssignee>;
type PersonName = keyof typeof people;
const labelColors: Record<string, string> = {
  Performance: "oklch(.65 .16 50)",
  Design: "oklch(.65 .16 350)",
  Feature: "oklch(.65 .16 290)",
  Sync: "oklch(.65 .16 250)",
  Bug: "oklch(.65 .16 25)",
  Docs: "oklch(.65 .16 90)",
};
function issue(
  number: number,
  title: string,
  priority: SexyTablePriority,
  state: SexyTablePullRequestState,
  estimate: number,
  label: string,
  due: string,
  assignees: readonly PersonName[],
): SexyTableIssue {
  return {
    id: `issue-${number}`,
    title,
    priority,
    pullRequest: { label: `#${number}`, state },
    estimate,
    label: { name: label, color: labelColors[label] ?? "currentColor" },
    due,
    assignees: assignees.map((name) => people[name]),
  };
}
export const initialGroups: readonly SexyTableGroup[] = [
  {
    id: "in-review",
    label: "In Review",
    icon: createElement(SexyTableStatusIcon, { status: "in-review" }),
    issues: [
      issue(
        1184,
        "Cache map tiles for the last region viewed",
        "medium",
        "open",
        2,
        "Performance",
        "Mar 12",
        ["Maya", "Leo"],
      ),
      issue(
        1179,
        "Write the copy for the location prompt",
        "low",
        "open",
        1,
        "Design",
        "Mar 6",
        ["Priya", "Harsh"],
      ),
      issue(
        1172,
        "Larger type in the route sheet",
        "medium",
        "draft",
        1,
        "Design",
        "Mar 6",
        ["Harsh", "Elena", "Tom"],
      ),
    ],
  },
  {
    id: "in-progress",
    label: "In Progress",
    icon: createElement(SexyTableStatusIcon, { status: "in-progress" }),
    issues: [
      issue(
        1168,
        "Resolve pin conflicts between devices",
        "urgent",
        "open",
        3,
        "Bug",
        "Mar 6",
        ["Leo", "Maya"],
      ),
      issue(
        1161,
        "Download regions over Wi-Fi only",
        "high",
        "draft",
        2,
        "Feature",
        "Mar 9",
        ["Elena"],
      ),
      issue(
        1157,
        "Invite people to a list by link",
        "medium",
        "closed",
        2,
        "Feature",
        "Mar 11",
        ["Tom", "Harsh", "Sam"],
      ),
    ],
  },
  {
    id: "todo",
    label: "Todo",
    icon: createElement(SexyTableStatusIcon, { status: "todo" }),
    issues: [
      issue(
        1150,
        "Drop deleted pins after thirty days",
        "medium",
        "draft",
        1,
        "Sync",
        "Apr 14",
        ["Sam", "Priya"],
      ),
      issue(
        1146,
        "Rotate the sync service’s signing keys",
        "high",
        "closed",
        1,
        "Sync",
        "Apr 14",
        ["Harsh", "Maya"],
      ),
      issue(
        1141,
        "Check contrast on the night map style",
        "low",
        "draft",
        1,
        "Design",
        "Apr 9",
        ["Priya"],
      ),
      issue(
        1137,
        "Restore a backup to a fresh account",
        "none",
        "open",
        2,
        "Bug",
        "Mar 18",
        ["Tom", "Elena"],
      ),
    ],
  },
  {
    id: "done",
    label: "Done",
    icon: createElement(SexyTableStatusIcon, { status: "done" }),
    issues: [
      issue(
        1129,
        "Measure the tile cache on a nearly full phone",
        "medium",
        "merged",
        3,
        "Performance",
        "Mar 2",
        ["Leo", "Harsh"],
      ),
      issue(
        1118,
        "Pick a storage engine for saved places",
        "high",
        "merged",
        1,
        "Docs",
        "Feb 26",
        ["Maya", "Sam", "Harsh"],
      ),
      issue(
        1104,
        "Decide who can edit a shared list",
        "low",
        "merged",
        1,
        "Feature",
        "Feb 20",
        ["Elena", "Priya"],
      ),
    ],
  },
];
